README.md
Add a status badge for the tests running in Travis CI.
=> Add travis badge to the readme

internals/crypto/rsa.go, internals/crypto/rsa_test.go, internals/crypto/symmetric.go, internals/crypto/symmetric_test.go
Created encode and decode functions to separate the encoding from marshaling to JSON.
=> Create encode and decode functions for ciphertexts

internals/api/user.go
This will be returned in the next version of the server.
=> Add EmailVerified field to api.User

pkg/secrethub/client.go, pkg/secrethub/fakeclient/client.go, pkg/secrethub/me.go
I've created a service that aliases `client.Repos().ListMine()` and `client.Users().Me()`.
I'll create another PR that adds `client.Me().SendVerficationEmail()`.
=> Create a client.Me() service to retrieve own user and repos

pkg/secrethub/client.go, pkg/secrethub/http.go, pkg/secrethub/me.go
~~#62 should be merged first.~~
=>  Add SendVerificationEmail function to the MeService 

internals/api/billing.go
Add a field to determine when a subscription will be cancelled.
=> Add CancelAt field SubscriptionFee

.travis.yml, README.md
=> Remove Travis-CI

internals/api/server_errors.go
To be used in secrethub/secrethub-cli#133
=> Add function to check whether error is of type not found to api pkg

internals/aws/service_creator.go, internals/crypto/rsa.go, internals/crypto/rsa_test.go, pkg/secrethub/account.go, pkg/secrethub/credentials/credentials.go, pkg/secrethub/credentials/encoding.go, pkg/secrethub/credentials/encoding_test.go, pkg/secrethub/credentials/rsa.go, pkg/secrethub/main_test.go, pkg/secrethub/user_test.go
=> Export verifier

internals/api/repo.go
=> Make repo created_at and last_modified_at non-optional

pkg/secrethub/fakeclient/secret.go, pkg/secrethub/secret.go
This makes it easier to use the client directly in applications.
=> Add Read and ReadString convenience functions

pkg/randchar/generator.go
Added the `human-readable` charset defined as `alphanumeric`-`similar`.
=> Add human-readable charset

.circleci/config.yml
Update the go version used in CI to 1.13.
=> Update go version to 1.13

.github/workflows/bump-version.yml
=> Automatically bump secrethub.ClientVersion on release branch

internals/api/paths.go
Previous message was incomplete and could be confusing.
=> Clarify invalid namespace error message

internals/oauthorizer/callback_handler.go
Otherwise cancelling the OAuth process results in a lame text-only page.
=> Also redirect errors in getting token to the custom result page

pkg/secrethub/fakeclient/client.go, pkg/secrethub/fakeclient/credential.go, pkg/secrethub/fakeclient/credentials.go, pkg/secrethub/fakeclient/idp_link.go, pkg/secrethub/fakeclient/me.go
This PR adds the 3 services to the fakeClient so that they can be mocked properly in the tests.
=> Adding CredentialServiceMeService and IDPLinkService to fake client

pkg/secrethub/account.go, pkg/secrethub/fakeclient/account.go
Reverts secrethub/secrethub-go#205
=> Revert "Add AccountService.Me() method"

internals/api/patterns.go
This gives some room to change them later server-side, while still
giving plenty of useful feedback to the user.
=> Loosen setup code validation

pkg/secrethub/client_options.go, pkg/secrethub/credentials/setup_code.go
As requested here: https://github.com/secrethub/secrethub-cli/pull/332#discussion_r469877042
=> Remove the with setup code option and make setup code credential provider
