secrethub/secrethub-go

.golangci.yml, internals/crypto/ciphertext.go, internals/crypto/scrypt.go, internals/crypto/scrypt_test.go, pkg/secrethub/account.go, pkg/secrethub/org_test.go, pkg/secrethub/user_test.go
Add the following linters:
- unused
- gosimple
- stylecheck
- structcheck
- varcheck
- interfacer
- unconvert
- ineffassign
- deadcode
- gocyclo
- typecheck
- depguard
- unparam
- nakedret
- gofmt
- misspell
- prealloc
- goconst
The last four found issues, which I've fixed.
=> Add more linters

internals/crypto/ciphertext.go
Because it is a map, not a list.
=> Rename metadataList to metadataMap

internals/crypto/ciphertext_test.go, internals/crypto/rsa.go, internals/crypto/symmetric_test.go
To make it possible to create them in other ways than decoding from a string.
=> Make the fields of CiphertextRSAAES public

pkg/secrethub/credential.go
It's a convenience variable that makes the developer experience
simpler and shorter. Before the developer was required to type:
```go
parser := secrethub.NewCredentialParser(secrethub.DefaultCredentialEncoders)
encoded, err := parser.Parse(credential)
```
Now the developer can just use this one line without having to think
about encoders:
```go
encoded, err := secrethub.DefaultCredentialParser.Parse(credential)
```
=> Add secrethub.DefaultCredentialParser

internals/api/account_key.go, internals/api/encrypted_data.go, internals/api/encrypted_data_test.go, internals/api/encryption_key.go, internals/api/encryption_metadata.go, internals/api/encryption_parameters.go, internals/api/values.go, pkg/secrethub/client.go, pkg/secrethub/credential.go
Rewrite of https://github.com/secrethub/secrethub-go/pull/87 after spec session with @mackenbach.
Implements the following spec:
```json
// AES-GCM
{
"algorithm": "aes-gcm",
"parameters": {
"nonce_length": 96,
},
"key": {
"type": "secret_key",
"length": 256,
"id": "<secret key id>"
},
"metadata": {
"nonce": "<nonce value>",
},
"ciphertext": "<ciphertext>",
},
// AES-GCM+SCRYPT
{
"algorithm": "aes-gcm",
"parameters": {
"nonce_length": 96,
},
"key": {
"type": "derived",
"length": 256,
"algorithm": "scrypt",
"parameters": {
"p": ,
"r": ,
"n": ,      
},
"metadata": {
"salt": "<salt>"
}
},
"metadata": {
"nonce": "<nonce value>",
},
"ciphertext": "<ciphertext>",
},
// RSA-OAEP
{
"algorithm": "rsa-oaep",
"parameters": {
"hashing_algorithm": "sha256"
},
"key": {
"type": "account_key",
"id": …
```
=> EncryptedData API type for account keys

pkg/secrethub/credential.go, pkg/secrethub/main_test.go
Since we are handling encoding and decoding here, passing around an interface is a pain. By saying these functions can only return RSACredential's, we remove a lot of the complexity. This is needed to make the CLI upgrade to the new version of secrethub-go a lot smoother.
In combination with https://github.com/secrethub/secrethub-cli/pull/104.
Tests still have to be fixed.
=> Return RSACredential instead of Credential

pkg/secrethub/fakeclient/client.go
So that the fake client always implements the client interface.
Tests that use functions that are not implemented on the fake will
fail with a nilpointer exception, while tests that do not use
unimplemented functions on the fake still compile and succeed.
=> Embed client in fake client

pkg/secrethub/internals/http/client.go
This used to trigger a stack overflow, as authenticating the request
triggered the creation of a new session, which is done in a request
which used to need authentication, which triggered this whole process
again.
=> Fix session refresh

pkg/secretpath/path.go, pkg/secretpath/path_test.go
This package implements utility functions for manipulating paths
compatible with SecretHub, e.g. namespaces, repositories, directories,
secrets and versions.
Had this one in the cooker for a while. Started it on a lazy sunday afternoon because I noticed we were doing quite some string manipulations in the Terraform provider and other projects that use the client library. 
The api.XXXPath types simply aren't usable enough so I tried to make something that is a bit more flexible. Inspired by Go's very own `filepath` [package](https://golang.org/pkg/path/filepath/).
=> Add pkg/secretpath

internals/api/credential.go, internals/api/credential_test.go, internals/api/user_test.go, internals/aws/service_creator.go, internals/aws/service_creator_test.go, pkg/secrethub/credentials/rsa.go, pkg/secrethub/user_test.go
Rename credential types as discussed last week.
The server contains compatibility code to maintain compatibility with clients `<=v0.20`.
=> Credential type rename

pkg/secrethub/internals/http/encoding.go
This hides useful information in resolving the problem.
=> Don't return an unexpected server error when the response cannot be parsed

internals/api/service.go
Use a value instead of pointer for created_by field of service,
as services are always created by an account. This field is not
optional.
=> Make created_by field of service non-optional

pkg/secrethub/internals/http/client.go
Don't add a query parameter when no subject types are given.
Request `/v1/namespaces/<workspace>/repos/<repo>/events` instead of `/v1/namespaces/<workspace>/repos/<repo>/events?subject_types=`.
=> Only add query params to request when not empty

pkg/secrethub/dir.go
It works just like mkdir -p, creating all directories that do not
exist yet recursively and it does not error when the directories
already exist.
=> Add CreateAll func to dir service to create dirs recursively

internals/api/credential.go, internals/api/credential_test.go, internals/api/patterns.go, internals/api/user_test.go, pkg/secrethub/credentials.go
For now we're not setting the credential name on a signup, as this is a backwards-incompatible change. We can later add the functionality to rename any credentials without a name.
=> Allow setting the credential description for new credentials

.circleci/config.yml, Makefile, scripts/check-version/check-version.sh, scripts/check-version/main.go
To prevent [this](https://github.com/secrethub/secrethub-go/blob/v0.24.0/pkg/secrethub/client_version.go#L5)
=> Verify client version is set correctly on release branches

pkg/secrethub/client.go
As is conventional for user agents. Instead of 
```
SecretHub/v1 secrethub-go/v0.26.0 secrethub-cli/0.34.0
```
This would result in
```
SecretHub/1.0 secrethub-go/0.26.0 secrethub-cli/0.34.0
```
=> Trim all v prefixes in user agent

pkg/secrethub/fakeclient/secret_version.go
The fake SecretVersionService was missing the `Iterator` function so a number of tests were failing. This PR adds the required function and fixes the issue.
=> Update fake SecretVersionService to match SecretVersionService interface

internals/api/server_errors.go, pkg/secrethub/secret_version.go
The `secret not found` error will now include the path of the secret. For example:
```
Encountered an error: cannot find secret: test/test/test, encountered error: Repo not found (server.repo_not_found)  (client.secret_not_found)
```
=> Update secret not found error message

pkg/secrethub/secret.go, pkg/secrethub/secret_version.go
Return `errSecretNotFound` from both `SecretVersionService` when secrets are listed and `SecretService` when get method is called.
The goal of this PR is to make the client always return `errSecretNotFound` when a secret is not found as opposed to a server error (`ErrSecretNotFound`) when listing secret versions and getting secrets and the client error: `errSecretNotFound` when getting secret versions.
=> Add secret path to all secret not found errors

pkg/secrethub/client.go, pkg/secrethub/client_options.go, pkg/secrethub/client_test.go
Passing app info to the client is now more extensible, so it can handle:
```
secrethub-go/0.27.0 secrethub-cli/0.37.0 secrethub-circleci-orb/1.0.0
```
Where the third layer comes from `SECRETHUB_APP_INFO_NAME`.
It can now also handle more layers of 'wrapped clients', e.g.: 
```
secrethub-go/0.27.0 secrethub-xgo/0.1.0 secrethub-java/0.2.0 jenkins-secrethub-plugin/1.0.0
```
But with greater extensibility, comes greater validation: when using `SECRETHUB_APP_INFO_NAME`, it ignores values if they don't match `[a-zA-Z0-9_-]` and when explicitly setting `WithAppInfo` it actually errors, because as an SDK consumer you'll want to immediately know if (and why) your supplied value didn't come through.
**Note**: there's no validation on the app info _version number_ at the moment, because next to the …
=> Make setting app info more extensible

pkg/secrethub/credentials/encoding.go
Return a `credential is malformed` error when credential payload is not a valid RSA private key instead of returning an `asn1: trailing data` or similar unhelpful error.
=> Malformed credential error

pkg/secrethub/credentials/sessions/session.go, pkg/secrethub/credentials/sessions/session_test.go
The previous check always returned true if the check was performed before the expiration. In most cases this did not hindered the actual functionality of the sessions because the session was just always refreshed. However, if a session was used after it was expired, the client wrongly assumed that the session was still valid, which led to a server error.
=> Fix session expiration check

internals/api/server_errors.go
See https://github.com/secrethub/secrethub-cli/pull/309.
=> Add server errors for taken service accounts

internals/gcp/errors.go
Before https://github.com/secrethub/secrethub-cli/pull/312 the not found error without a message was returned to the user on invalid keyring: `Encountered an error:  (gcp.not_found) `. We should aim never to return these vague errors to the user, but just to be on the safe side for when they do occur, having an actual error message to show would be nice.
=> Add a message to GCP errors without a message

README.md
This should fix the security warning given by Chrome when accessing: https://pkg.go.dev/github.com/secrethub/secrethub-go?tab=overview
=> Make godoc badge link https

pkg/secrethub/fakeclient/credentials.go, pkg/secrethub/fakeclient/idp_link.go
In fakeclient, both credentials and IDPLink have a function `List` that returns an iterator. However, currently, the user cannot mock the iterator itself.
Therefore, this PR enables the user to mock these to make testing of these functions smoother.
This PR tackles the following PR from the CLI: https://github.com/secrethub/secrethub-cli/pull/329
=> Add iterators for idplink and credentials

go.mod, internals/api/patterns.go, pkg/secrethub/client.go, pkg/secrethub/client_options.go, pkg/secrethub/credentials.go, pkg/secrethub/credentials/setup_code.go, pkg/secrethub/internals/http/client.go
This PR adds the `WithSetupCode` client option, that makes the client use the supplied setup code for authorizing its requests.
=> Allow acount key creation with setup code

internals/api/credential.go, internals/api/service.go, pkg/secrethub/account.go, pkg/secrethub/service.go, pkg/secrethub/user.go, pkg/secrethub/user_test.go
This merge request removes the separate `createAccountKeyRequest` and embeds the account key into the `createCredentialRequest`.
This is done to prevent ending up with unusable accounts if the `createAccountKey` request fails.
=> Create account along with key in one atomic request

pkg/secrethub/client.go, pkg/secrethub/client_options.go
This allows setting a passphrase without having to provide a credential itself, which can be used to make configuring the Terraform provider easier.
=> Add option set set a default passphrase reader

pkg/secrethub/client.go, pkg/secrethub/client_options.go, pkg/secrethub/configdir/dir.go, pkg/secrethub/credentials/encoding.go, pkg/secrethub/credentials/key.go, pkg/secrethub/credentials/providers.go, pkg/secrethub/credentials/readers.go
This PR:
- improves the error returned when the credential is password-protected, but no passphrase reader is provided.
- wraps all errors that occur when loading a credential with a message that includes the credential's source
- adds the `SECRETHUB_CREDENTIAL_PASSPHRASE` environment variable, which is checked if no passphrase reader is provided, but the credential is password-protected
=> Improve Credential Errors

pkg/secrethub/client.go
Just like the CLI already checks the `SECRETHUB_API_REMOTE` envvar, the SDK now also accepts the same envvar.
This also makes it possible to use this envvar in other projects, for example the [Terraform provider](https://github.com/secrethub/terraform-provider-secrethub), if they upgrade the SDK to a version including this commit.
=> Configure the remote server with SECRETHUB_API_REMOTE envvar

internals/errio/errors.go
This allows displaying the original error without any other text, while not breaking the existing contract of throwing UnexpectedErrors.
As an alternative solution to https://github.com/secrethub/secrethub-go/pull/224
=>  Allow UnexpectedError to be unwrapped to wapped error

pkg/secrethub/client.go, pkg/secrethub/client_test.go, pkg/secrethub/credentials/key.go
There were two cases where either no error or an useless error were returned in the process of loading a credential:
- If no passphrase was provided when using the SDK, this error would get ignored altogether. This is fixed by 8a82982.
- After this was fixed, not setting a passphrase would lead to an "invalid passphrase" error instead of a "no passphrase provided error. This is fixed by 1a490aa (`passphraseReader` is now `nil` again in all cases that no passphrase is provided)
- If an invalid passphrase was provided through the environment, a crypto error would be returned. This is fixed by 9f74af2.
=> Fix error handling of credential loading

pkg/secrethub/acl.go, pkg/secrethub/acl_test.go
In order to check if the optimisation is effectual, I have run the following script, which populated the priorly created `optimization-test` directory with 1000 secrets:
```go
u, err := secrethub.NewClient()
if err != nil {
fmt.Print(err.Error())
}
iterations := 1000
for i := 0; i < iterations; i++ {
_, err := u.Secrets().Write(fmt.Sprintf("<SECRETHUB NAMESPACE>/optimization/optimization-test/secret%d", i), []byte(fmt.Sprintf("value%d", i)))
if err != nil {
fmt.Print(err.Error())
}
}
```
I have then replaced the CLI's SDK dependency by pasting the following in CLI project's `go.mod`:
```
replace (
github.com/secrethub/secrethub-go => <RELATIVE PATH TO secrethub-go FOLDER>  // in my case, ../secrethub-go
)
```
and then I rebuilt the CLI.
NB, I was on the `feature/refactor-and-test-acl` …
=> Improve performance of creating access rules

pkg/secrethub/account.go, pkg/secrethub/fakeclient/account.go, pkg/secrethub/internals/http/client.go
This PR adds a `Delete` method to the account service, that deletes the currently authenticated account.
To prevent users from calling this method accidentally, the method requires you to pass your own account id as parameter.
=> Account delete
